


all:	
		g++ -o test ../utilities/RPNNotation.o ../utilities/ShuntingYard.o compCRPNExpression.cpp compCRPNTest.cpp
		g++ -o test2 ../utilities/RPNNotation.o ../utilities/ShuntingYard.o compCRPNExpression.cpp compCRPNTestF.cpp
